### ISSUE TITLE
EmailAddress Orphan Instances

### ISSUE THREAD

**Issue by gregwebs** [adinapoli/mandrill#18]
I ran into an Orphan collision. I may need to resolve it by importing the orphan from this package at a point lower in the dependency tree then I would like.

A library should avoid orphans whenever possible. What is this needed for? I am wondering if you can more or less inline the To/From JSON definition for EmailAddress wherever it is needed.

An alternative is to centralize the orphans either by putting them into the email-validate package itself or by creating an email-validate-orphans package.

**Comment by adinapoli** [comment]
Hey Greg,

You're right, it's quite lame to have orphan collision. I'm out of town and
from mobile, so sorry if my writing style it's a bit sloppy. I guess you
are referring to this one:

https://github.com/adinapoli/mandrill/blob/master/src/Network/API/Mandrill/Orphans.hs

As you can see, I had already anticipated possible clashes and put the
orphans in a separate module you can choose not to import. I think the
problem then is that in my top level module I am importing this as well,
and not doing will give the user a compile error he might be scratching his
head on. The way I see it, there are two solutions:

1. Do not import automatically that Orphans module, do that only when
needed.

2. Create a newtype wrapper "MandrillEmail" or similar and derive the json
for it.

Despite I generally try to not go wild with newtypes proliferation, it
feels like the best solution, so that we can make that field opaque and we
can swap implementation in the future if we want.

Both solutions will break existing user code, so we should keep this in
mind.

As a last note, if memory does not betray me, inlining was not an option as
the mandrill payload are quite big and to ease the pain I have used Aeson's
TH derivation for them.

Wdyt? I would be very keen on accepting pull requests, of course ;)

Alfredo

**Comment by gregwebs** [comment]
> As you can see, I had already anticipated possible clashes and put the orphans in a separate module you can choose not to import. 

typeclass instances are global (and follow the value), so a separate module doesn't solve the problem.

I would use -ddump-splices to get what TH generates, and then inline the Email JSON instance code.
AFAICT you only need to write an instance manually for `MandrillRecipient` and the TH derivation is already fragile by using `drop 6`

**Comment by adinapoli** [comment]
Ouch, I always thought that using an orphan module would solve such a problem, so TIL something new, thanks for that!

Your plan sounds good, probably we can fix the clash by unrolling MandrillRecipient as you suggested.

I will try to release a new version this weekend, unless you beat me with a PR ;)

Thanks!
Alfredo

**Comment by gregwebs** [comment]
actually, it is mis-leading to say that an orphan follows the value. A module with an orphan instance has to be used, so it has to be imported into another module. The main thing is that typeclass instances are always automatically exported. So importing a Mandrill module imports the instance.

**Comment by adinapoli** [comment]
@gregwebs Twist of the plot: `EmailAddress` is actually used for `MandrillMessage` as well. I have tried to dump the TH of the `deriveJSON` call, but honestly it's ungodly.

I have unrolled manually `MandrillRecipient` with ease, but I do not want to do the same for the `MandrillMessage` payload. So I'm leaning towards the `newtype` wrapper around `EmailMessage` and deriving the instances for those.

What do you think?

**Comment by adinapoli** [comment]
Fixed in 0.3.0.0.
