### ISSUE TITLE
Bump aeson dependency

### ISSUE THREAD

**Issue by tom-audm** [adinapoli/mandrill#58]
Aeson 1.5 is almost a year and a half old - can we bump this dependency?

**Comment by adinapoli** [comment]
Hey,

I am on holiday at the moment, so I have limited Internet access. I can't remember on top of my head if the aeson bound was introduced as a precaution or because this library genuinely needs to be patched to support newer aeson.

In the former case, I can simply publish a Hackage revision to bump the upper bound. Have you tried building the library with newer version using `allow-newer` or similar? Did it work?
